-- Store SEC XBRL facts as typed values. Vector retrieval may discover a
-- relevant statement, but arithmetic and period comparisons use this table.

create table if not exists public.financial_facts (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  taxonomy text not null,
  concept text not null,
  label text not null,
  description text,
  unit text not null,
  value numeric not null,
  period_start date not null,
  period_end date not null,
  fiscal_year integer,
  fiscal_period text,
  form text not null check (form in ('10-K', '10-Q', '8-K', '20-F', '40-F', '6-K')),
  filed_at date not null,
  accession_number text not null,
  frame text,
  source_url text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (
    stock_id,
    taxonomy,
    concept,
    unit,
    period_start,
    period_end,
    accession_number
  )
);

create index if not exists financial_facts_lookup_idx
  on public.financial_facts (
    stock_id,
    concept,
    period_end desc,
    filed_at desc
  );

alter table public.financial_facts enable row level security;

drop policy if exists "Public financial facts are readable"
  on public.financial_facts;
create policy "Public financial facts are readable"
  on public.financial_facts for select using (true);

grant select on table public.financial_facts to anon, authenticated;
