-- AI Bull vs Bear database schema for Supabase.
-- Run this in the Supabase SQL Editor after enabling the pgvector extension.

create extension if not exists vector;

create table if not exists public.stocks (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  company_name text not null,
  exchange text not null,
  sector text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.watchlists (
  user_id uuid not null references auth.users(id) on delete cascade,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, stock_id)
);

create table if not exists public.stock_prices (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  trading_date date not null,
  open numeric(14, 4) not null,
  high numeric(14, 4) not null,
  low numeric(14, 4) not null,
  close numeric(14, 4) not null,
  volume bigint not null,
  unique (stock_id, trading_date)
);

create table if not exists public.technical_indicators (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  trading_date date not null,
  rsi numeric(8, 4),
  macd numeric(14, 6),
  macd_signal numeric(14, 6),
  moving_average_20 numeric(14, 6),
  moving_average_50 numeric(14, 6),
  volatility numeric(8, 4),
  volume_spike boolean not null default false,
  unique (stock_id, trading_date)
);

create table if not exists public.evidence_documents (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  source_type text not null check (source_type in ('news', 'filing', 'technical')),
  external_id text,
  title text not null,
  url text,
  published_at timestamptz,
  raw_text text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.evidence_chunks (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.evidence_documents(id) on delete cascade,
  chunk_text text not null,
  embedding vector(1536),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists evidence_chunks_embedding_idx
  on public.evidence_chunks using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create table if not exists public.analysis_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  question text,
  final_summary text,
  guardrail_status text not null default 'passed',
  risk_level text,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_outputs (
  id bigint generated by default as identity primary key,
  analysis_run_id uuid not null references public.analysis_runs(id) on delete cascade,
  agent_name text not null,
  output_json jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.claim_evidence (
  claim_id text not null,
  analysis_run_id uuid not null references public.analysis_runs(id) on delete cascade,
  evidence_document_id bigint not null references public.evidence_documents(id) on delete cascade,
  primary key (claim_id, evidence_document_id)
);

create table if not exists public.token_usage (
  id bigint generated by default as identity primary key,
  analysis_run_id uuid not null references public.analysis_runs(id) on delete cascade,
  model_name text not null,
  prompt_tokens integer not null default 0,
  completion_tokens integer not null default 0,
  total_tokens integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.watchlists enable row level security;
alter table public.analysis_runs enable row level security;
alter table public.agent_outputs enable row level security;
alter table public.token_usage enable row level security;

create policy "Users can manage their own watchlist"
  on public.watchlists for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can read their own analysis runs"
  on public.analysis_runs for select
  using (auth.uid() = user_id);

create policy "Users can create their own analysis runs"
  on public.analysis_runs for insert
  with check (auth.uid() = user_id);

create policy "Users can read outputs for their analysis runs"
  on public.agent_outputs for select
  using (
    exists (
      select 1 from public.analysis_runs
      where analysis_runs.id = agent_outputs.analysis_run_id
        and analysis_runs.user_id = auth.uid()
    )
  );

create policy "Users can read token usage for their analysis runs"
  on public.token_usage for select
  using (
    exists (
      select 1 from public.analysis_runs
      where analysis_runs.id = token_usage.analysis_run_id
        and analysis_runs.user_id = auth.uid()
    )
  );
