-- AI Bull vs Bear database schema for Supabase.
-- Run this in the Supabase SQL Editor after enabling the pgvector extension.

create extension if not exists vector;

create table if not exists public.stocks (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  company_name text not null,
  exchange text not null,
  sector text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.watchlists (
  user_id uuid not null references auth.users(id) on delete cascade,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, stock_id)
);

create table if not exists public.stock_prices (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  trading_date date not null,
  open numeric(14, 4) not null,
  high numeric(14, 4) not null,
  low numeric(14, 4) not null,
  close numeric(14, 4) not null,
  volume bigint not null,
  unique (stock_id, trading_date)
);

create table if not exists public.technical_indicators (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  trading_date date not null,
  rsi numeric(8, 4),
  macd numeric(14, 6),
  macd_signal numeric(14, 6),
  moving_average_20 numeric(14, 6),
  moving_average_50 numeric(14, 6),
  volatility numeric(8, 4),
  volume_spike boolean not null default false,
  unique (stock_id, trading_date)
);

create table if not exists public.financial_facts (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  taxonomy text not null,
  concept text not null,
  label text not null,
  description text,
  unit text not null,
  value numeric not null,
  period_start date not null,
  period_end date not null,
  fiscal_year integer,
  fiscal_period text,
  form text not null check (form in ('10-K', '10-Q', '8-K', '20-F', '40-F', '6-K')),
  filed_at date not null,
  accession_number text not null,
  frame text,
  source_url text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (
    stock_id,
    taxonomy,
    concept,
    unit,
    period_start,
    period_end,
    accession_number
  )
);

create index if not exists financial_facts_lookup_idx
  on public.financial_facts (
    stock_id,
    concept,
    period_end desc,
    filed_at desc
  );

create table if not exists public.evidence_documents (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  source_type text not null check (source_type in ('news', 'filing', 'technical')),
  external_id text,
  title text not null,
  url text,
  published_at timestamptz,
  raw_text text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists evidence_documents_external_id_idx
  on public.evidence_documents (external_id);

create table if not exists public.evidence_chunks (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.evidence_documents(id) on delete cascade,
  chunk_text text not null,
  embedding vector(1536),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists evidence_chunks_embedding_idx
  on public.evidence_chunks using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create table if not exists public.macro_series (
  code text primary key,
  name text not null,
  source text not null check (source in ('fred', 'eia', 'treasury', 'fomc', 'cme')),
  unit text not null,
  frequency text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.macro_observations (
  series_code text not null references public.macro_series(code) on delete cascade,
  observation_date date not null,
  value numeric not null,
  metadata jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz not null default now(),
  primary key (series_code, observation_date)
);

create index if not exists macro_observations_recent_idx
  on public.macro_observations (series_code, observation_date desc);

create table if not exists public.embedding_profiles (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  provider text not null,
  model text not null,
  dimensions integer not null check (dimensions between 1 and 16000),
  distance_metric text not null default 'cosine'
    check (distance_metric in ('cosine', 'inner_product', 'l2')),
  normalization text not null default 'none',
  modality text not null default 'text'
    check (modality in ('text', 'multimodal')),
  query_instruction text,
  document_instruction text,
  preprocessing_version text not null default 'v1',
  status text not null default 'test'
    check (status in ('test', 'active', 'retired')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.embedding_profiles (
  id,
  slug,
  provider,
  model,
  dimensions,
  distance_metric,
  normalization,
  modality,
  preprocessing_version,
  status,
  metadata
)
values (
  '00000000-0000-4000-8000-000000001536',
  'local-hash-v1',
  'postgres',
  'local_text_embedding',
  1536,
  'cosine',
  'none',
  'text',
  'word-hash-v1',
  'active',
  '{"purpose":"offline integration baseline","semantic_model":false}'::jsonb
)
on conflict (slug) do nothing;

create table if not exists public.chunk_embeddings (
  chunk_id bigint not null references public.evidence_chunks(id) on delete cascade,
  profile_id uuid not null references public.embedding_profiles(id) on delete cascade,
  embedding vector not null,
  input_hash text not null,
  created_at timestamptz not null default now(),
  primary key (chunk_id, profile_id)
);

create table if not exists public.analysis_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  question text,
  final_summary text,
  guardrail_status text not null default 'passed',
  risk_level text,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_outputs (
  id bigint generated by default as identity primary key,
  analysis_run_id uuid not null references public.analysis_runs(id) on delete cascade,
  agent_name text not null,
  output_json jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.claim_evidence (
  claim_id text not null,
  analysis_run_id uuid not null references public.analysis_runs(id) on delete cascade,
  evidence_document_id bigint not null references public.evidence_documents(id) on delete cascade,
  primary key (claim_id, evidence_document_id)
);

create table if not exists public.token_usage (
  id bigint generated by default as identity primary key,
  analysis_run_id uuid not null references public.analysis_runs(id) on delete cascade,
  model_name text not null,
  prompt_tokens integer not null default 0,
  completion_tokens integer not null default 0,
  total_tokens integer not null default 0,
  created_at timestamptz not null default now()
);

-- The project disables "Automatically expose new tables", so Data API access
-- is granted explicitly. Public market/evidence data is read-only. User-owned
-- records still require an authenticated JWT and are constrained by RLS below.
grant usage on schema public to anon, authenticated;

-- Server-only secret keys map to service_role. This role still needs SQL
-- privileges even though it bypasses RLS.
grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;

alter default privileges in schema public
  grant all privileges on tables to service_role;
alter default privileges in schema public
  grant all privileges on sequences to service_role;

grant select on table
  public.stocks,
  public.stock_prices,
  public.technical_indicators,
  public.financial_facts,
  public.evidence_documents,
  public.evidence_chunks,
  public.macro_series,
  public.macro_observations,
  public.embedding_profiles,
  public.chunk_embeddings
to anon, authenticated;

grant select, insert, delete on table public.watchlists to authenticated;
grant select, insert on table public.analysis_runs to authenticated;
grant select on table
  public.agent_outputs,
  public.claim_evidence,
  public.token_usage
to authenticated;

alter table public.watchlists enable row level security;
alter table public.analysis_runs enable row level security;
alter table public.agent_outputs enable row level security;
alter table public.token_usage enable row level security;
alter table public.macro_series enable row level security;
alter table public.macro_observations enable row level security;

create policy "Public macro series are readable"
  on public.macro_series for select using (true);

create policy "Public macro observations are readable"
  on public.macro_observations for select using (true);

create policy "Users can manage their own watchlist"
  on public.watchlists for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can read their own analysis runs"
  on public.analysis_runs for select
  using (auth.uid() = user_id);

create policy "Users can create their own analysis runs"
  on public.analysis_runs for insert
  with check (auth.uid() = user_id);

create policy "Users can read outputs for their analysis runs"
  on public.agent_outputs for select
  using (
    exists (
      select 1 from public.analysis_runs
      where analysis_runs.id = agent_outputs.analysis_run_id
        and analysis_runs.user_id = auth.uid()
    )
  );

create policy "Users can read token usage for their analysis runs"
  on public.token_usage for select
  using (
    exists (
      select 1 from public.analysis_runs
      where analysis_runs.id = token_usage.analysis_run_id
        and analysis_runs.user_id = auth.uid()
    )
  );
